//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotter.Framework.EF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spotter.Framework.EF.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument could not be equal to its default value..
        /// </summary>
        public static string ArgumentCouldNotBeDefault {
            get {
                return ResourceManager.GetString("ArgumentCouldNotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed entity could not be removed..
        /// </summary>
        public static string ArgumentCouldNotBeRemoved {
            get {
                return ResourceManager.GetString("ArgumentCouldNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed entity could not be added or updated..
        /// </summary>
        public static string ArgumentCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("ArgumentCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Context cannot be null.
        /// </summary>
        public static string DbContextNull {
            get {
                return ResourceManager.GetString("DbContextNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed for one or more entities..
        /// </summary>
        public static string DbEntityValidationException {
            get {
                return ResourceManager.GetString("DbEntityValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity framework data access operation could not be executed. Please see the inner exception for additional information.
        /// </summary>
        public static string EntityExceptionOccured {
            get {
                return ResourceManager.GetString("EntityExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided key of type &apos;{0}&apos; is not assignable to the expected entity key of type &apos;{1}&apos; with name &apos;{2} &apos;.
        /// </summary>
        public static string EntityKeyTypeMismatch {
            get {
                return ResourceManager.GetString("EntityKeyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity of type &apos;{0}&apos; is not supported by the repository.
        /// </summary>
        public static string EntityNotSupportedByRepository {
            get {
                return ResourceManager.GetString("EntityNotSupportedByRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity set &apos;{0}&apos; could not be found in container &apos;{1}&apos;.
        /// </summary>
        public static string EntitySetCouldNotBeFound {
            get {
                return ResourceManager.GetString("EntitySetCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception can not be swallowed.
        /// </summary>
        public static string ExceptionCanNotBeSwallowed {
            get {
                return ResourceManager.GetString("ExceptionCanNotBeSwallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided composite key of type &apos;{0}&apos; does not provide any of the expected properties:  &apos;{1}&apos;. The problem occurs because the properties of the composite key object does not match to the key properties defined in EntitySet &apos;{2}&apos;.
        /// </summary>
        public static string MissingCompositeKeyProperties {
            get {
                return ResourceManager.GetString("MissingCompositeKeyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity set &apos;{0}&apos; without specified element type is not supported.
        /// </summary>
        public static string MissingElementType {
            get {
                return ResourceManager.GetString("MissingElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity set &apos;{0}&apos; has an invalid element type becaue the element type does not have any keys specified.
        /// </summary>
        public static string MissingKeysForElementType {
            get {
                return ResourceManager.GetString("MissingKeysForElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate not provided in specification. .
        /// </summary>
        public static string MissingPredicate {
            get {
                return ResourceManager.GetString("MissingPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided composite key of type &apos;{0}&apos; does not provide some of the expected properties:  &apos;{1}&apos; defined in EntitySet &apos;{2}&apos;.
        /// </summary>
        public static string MissingSomeOfTheCompositeKeyProperties {
            get {
                return ResourceManager.GetString("MissingSomeOfTheCompositeKeyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object of type &apos;{0}&apos; does not longer exists..
        /// </summary>
        public static string ObjectDoesNotLongerExists {
            get {
                return ResourceManager.GetString("ObjectDoesNotLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity was modified or deleted in the meantime by an other transaction.
        /// </summary>
        public static string OptimisticConcurencyException {
            get {
                return ResourceManager.GetString("OptimisticConcurencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFRepository  update method is not supported for type  &apos;{0}&apos;. Update method is supported only for types that derive from EntityObject.
        /// </summary>
        public static string UpdateMethodNotSupported {
            get {
                return ResourceManager.GetString("UpdateMethodNotSupported", resourceCulture);
            }
        }
    }
}
